name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"   # Roda todo dia à meia-noite
  workflow_dispatch:       # Permite rodar manualmente pelo GitHub Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull --rebase origin HEAD
          git add -A .
          git commit -m "update profile 3d" || echo "No changes to commit"
          git push origin HEAD
            